parameters:
    libeo_api.serializer.normalizer.category.class: Libeo\Bundle\ApiBundle\Normalizer\LibeoApiCategoryNormalizer

services:
    # Normalizers

    pim_webservice.serializer.normalizer.category:
        class: %libeo_api.serializer.normalizer.category.class%
        tags:
            - { name: pim_webservice.serializer.normalizer, priority: 90 }
        arguments:
            - '@pim_serializer.normalizer.label_translation'
