parameters:
    libeo_api.serializer.class: Symfony\Component\Serializer\Serializer

services:
    libeo_api.serializer:
        class:  %libeo_api.serializer.class%

    libeo_api.serializer.encoder.json:
        public: false
        class: %libeo_serializer.encoder.json.class%
        tags:
            - { name: libeo_api.serializer.encoder, priority: 90 }