parameters:
    libeo_api.serializer.normalizer.category.class: Libeo\Bundle\ApiBundle\Normalizer\LibeoApiCategoryNormalizer
    libeo_api.serializer.normalizer.media.class: Libeo\Bundle\ApiBundle\Normalizer\LibeoApiMediaNormalizer
    libeo_api.serializer.normalizer.product.class: Libeo\Bundle\ApiBundle\Normalizer\LibeoApiProductNormalizer

services:
    # Normalizers

    pim_webservice.serializer.normalizer.category:
        class: %libeo_api.serializer.normalizer.category.class%
        tags:
            - { name: pim_webservice.serializer.normalizer, priority: 90 }
        arguments:
            - '@pim_serializer.normalizer.label_translation'

    pim_webservice.serializer.normalizer.media:
        class: %libeo_api.serializer.normalizer.media.class%
        tags:
            - { name: pim_webservice.serializer.normalizer, priority: 90 }
        arguments:
            - '@router'

    pim_webservice.serializer.normalizer.product:
        class: %libeo_api.serializer.normalizer.product.class%
        calls:
            - [setFilters, [['@pim_serializer.filter.product_value']]]
        tags:
            - { name: pim_webservice.serializer.normalizer, priority: 90 }