parameters:
#    libeo_api.example.class: Libeo\Bundle\ApiBundle\Example

services:
#    libeo_api.example:
#        class: %libeo_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
